### PR TITLE
Php8.1

### LINKED ISSUE #129: Compatibility with Magento 2.4.4 and Php 8.1
Issue Brief
--
Most recent Magento version (2.4.4) requires Php 8.1. Tweakwise Export module however is not compatible with Php 8.1.

Environment
--
- [ ] PHP Version: 8.1
- [ ] Magento Version: 2.4.4
- [ ] Tweakwise Export Version: 2.4.1 (latest)

Steps to reproduce
--
1. Install Magento 2.4.4 on Php 8.1.from `develop` branch.
2. Run `bin/magento setup:di:compile` on command line.

Actual result
--
Errors are thrown like:
1. `Fatal error: During inheritance of IteratorAggregate: Uncaught Exception: Deprecated Functionality: Return type of Emico\TweakwiseExport\Model\Write\EavIterator::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice.`
2. `Fatal error: During inheritance of IteratorAggregate: Uncaught Exception: Deprecated Functionality: Return type of Emico\TweakwiseExport\Model\Write\Products\Collection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice. `

Might also be other issues. Module needs to be thoroughly tested on php 8.1.

Expected result
--
Module working with Php 8.1.

### PR DESCRIPTION
**Pull request by ahuininga-orisha**
- Added Php 8.1 support
- Bumped version number for new release to 4.2.0
- Added return type wil change to one function to keep support for php 7.4. If support for php 7.4 is dropped this can be fixed properly

fixes #129

### CODE REVIEW

File: Model/Write/Products.php [hunk 1]
```diff
@@ -266,7 +266,11 @@ protected function scalarValue($value)
             $value = $this->normalizeExponent($value);
         }
 
-        return html_entity_decode($value, ENT_NOQUOTES | ENT_HTML5);
+        if (!empty($value)) {
```
Comment (bramstroker) [inline Model/Write/Products.php:269]: @ah-net I think this change causes another regression we had in our shop with 4.2.0, where almost all our products were exported with `<stock/>` instead of `<stock>0</stock>` causing the feed to not be validated correctly.

0 is also empty.

Comment (ahuininga-orisha) [reply Model/Write/Products.php:269]: Your right. Ill make an pull request

Comment (ahuininga-orisha) [reply Model/Write/Products.php:269]: Made an pull request #134
